#!/usr/bin/env perl

use strict;
use warnings;
use autodie qw( :all );

use Path::Class qw( dir );

system( qw( prove -vm t/00-prereq.t ) );

for my $t_file (
    sort grep { !$_->is_dir() && $_->basename() =~ /^(?:0[1-9]|[1-9])/ }
    dir('t')->children() ) {

    ( my $t_less = $t_file->basename() ) =~ s/\.t$//;

    my $lib = dir('answers')->subdir($t_less);

    die "No lib dir for $t_file" unless -d $lib;

    system( 'prove', '-I', $lib, '-vm', $t_file );
}
